[default_session]
startup_command = "~/.config/sesh/scripts/default"

[[session]]
name = "ğŸ Home"
path = "~"

# [[session]]
# name = "ğŸª´Evo"
# path = "~/dev"
# startup_script = "~/.config/sesh/scripts/s"

[[session]]
name = "âš™ï¸ Dotfiles"
path = "~/.dotfiles"
startup_command = "m -c ':Telescope find_files'"
